"""added the duration

Revision ID: 976495c644da
Revises: 9c57bdfef487
Create Date: 2025-05-01 13:29:17.648567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976495c644da'
down_revision = '9c57bdfef487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('workout_plan_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('workout_plan_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    # ### end Alembic commands ###
