"""Add date, progress, and calories fields to WorkoutPlan

Revision ID: 9e558a834607
Revises: 2e286750ba7f
Create Date: 2025-05-05 12:23:55.708684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e558a834607'
down_revision = '2e286750ba7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.drop_column('calories')
        batch_op.drop_column('progress')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
